<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Repository\RepositoryTrait\FilterRepositoryTrait;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    use FilterRepositoryTrait;

    public function findAllByParameters($filter, $order) {
        $qb   = $this->createQueryBuilder('t');

        if ($filter !== null) {
            $this->addTextSearch(
                $qb,
                $this->getFilterArrayByFieldNames(['title', 'description', 'extract'], $filter)
            );
        }

        if ($order !== null) {
            $this->addOrdering(
                $qb,
                $order
            );
        }

        return $qb->getQuery();
    }
}
