<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Repository\RepositoryTrait\FilterRepositoryTrait;
/**
 * GaleryImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryImageRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy([], ['order' => 'ASC', 'id' => 'ASC']);
    }
}
