db:
    driver: %database_driver%
    host: %database_host%
    port: %database_port%
    dbname: %database_name%
    user: %database_user%
    password: %database_password%

mail:
    swift_options:
        encryption: ssl
        host: %mailer_host% # On production, this must be "localhost", or mail sending will timeout.
        port: ~
        username: %mailer_user%
        password: %mailer_password%
    swift_use_spool: %swift_use_spool% # Look in the ApiController for explanation

app:
    name: %app_name% # Used by monolog
    maintenance: %maintenance%
    contact_form_target: %contact_form_target%
    # To obtain Google reCAPTCHA keys, register a new site as "localhost" on
    # https://www.google.com/recaptcha
    recaptcha:
        site_key: ~
        secret_key: ~
    admin:
        result_page_size: 20

monolog:
    slack_handler:
        token: %xoxb-4605888119-NmB6S0W4LrxkQnXOVLAxgsdH%
        channel: %monolog_slack_handler_channel%
    # Only needed if the SwiftMailer Handler is added to the monolog logger
    # swift_mailer_handler:
    #     critical_error_notification_to: error@zalehy.com

# Configurations declared here are registered in the app container under the
# "config" key. Ex: "mainenance" is available via: `$app['config']['maintenance']`.
google_analytics_id: %google_analytics_id%

# Available versions for the "/api/{v}" routes.
# The last entry counts as the latest API version, which is used in the
# JS modules, when no explicit api version is provided. (ajax.js)
api_versions:
    - 1

# There's no need to change the asset_version manually.
# It will be the unix timestamp when building the project before deployment.
asset_version: 1

# The first is the default locale
locales:
    - hu

one_sky_helper:
    api_key: %one_sky_api_key%
    api_secret: %one_sky_api_secret%
    project_id: %one_sky_project_id%

trans_download_command:
    # This path is relative to the project's root dir.
    local_download_path: src/translations
    # Changes in the 'locale_dir_prefix' parameter must be in sync with the
    # .gitignore file in the translations dir.
    locale_dir_prefix: onesky_

# Specific configuration for the zeecoder/mailchimp-handler Helper.php
# constructor
mailchimp_helper:
    secret_api: %mailchimp_secret_api%

# App-specific mailchimp configurations
mailchimp:
    list_id: %mailchimp_list_id%


